name: FindOnRent Deployment

on:
  push:
    branches: [ "development" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v3

      - name: ğŸ” Connect to server and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /var/www/findonrent.com/html

            # Pull latest code
            git reset --hard
            git pull origin development

            # Build frontend
            cd frontend
            # npm install --legacy-peer-deps
            npm run build

            # Build backend
            cd ../backend
            # npm install --omit=dev

            # Restart services
            pm2 restart frontend
            pm2 restart backend
